"""Remediation walkthrough loading and the code->walkthrough reverse index.

Walkthroughs live in guides/remediation/*.md and declare which finding codes
they remediate via a front-matter `remediates: [codes]` list. This module
builds a reverse index {code: Guide} at startup, first-wins on conflict.
"""

import logging
from pathlib import Path

from rescue.guides import Guide, load_guide

logger = logging.getLogger(__name__)


def load_remediation_walkthroughs(remediation_dir: Path) -> dict[str, Guide]:
    """Scan a directory of walkthrough markdown files, return {code: Guide}.

    First-wins on a code claimed by two files (sorted by filename); a warning
    is logged. Files with no `remediates` entries are skipped with a warning.
    A missing directory yields an empty index (no error).
    """
    index: dict[str, Guide] = {}
    if not remediation_dir.is_dir():
        return index
    for path in sorted(remediation_dir.glob("*.md")):
        try:
            guide = load_guide(path)
        except Exception as e:  # malformed front-matter etc.
            logger.warning("Skipping unparseable walkthrough %s: %s", path.name, e)
            continue
        if not guide.remediates:
            logger.warning("Walkthrough %s declares no `remediates` codes", path.name)
            continue
        for code in guide.remediates:
            if code in index:
                logger.warning(
                    "Code %s already remediated by an earlier walkthrough; "
                    "ignoring duplicate in %s", code, path.name)
                continue
            index[code] = guide
    return index


def walkthrough_for(index: dict[str, Guide], code: str | None) -> Guide | None:
    """Resolve a finding code to its walkthrough, or None."""
    if not code:
        return None
    return index.get(code)


def build_catalog(modules, index: dict[str, "Guide"]) -> list[dict]:
    """One row per declared code across all modules, sorted by code."""
    rows: list[dict] = []
    for mod in modules:
        for code in getattr(mod, "emits_codes", []):
            guide = index.get(code)
            rows.append({
                "code": code,
                "module": mod.name,
                "walkthrough_title": guide.title if guide is not None else None,
            })
    rows.sort(key=lambda r: r["code"])
    return rows


def render_catalog_markdown(rows: list[dict]) -> str:
    covered = sum(1 for r in rows if r["walkthrough_title"])
    lines = [
        "# Remediation Catalog",
        "",
        "> Generated by `rescue remediation-catalog`. Do not edit by hand.",
        "",
        f"{len(rows)} codes, {covered} with walkthroughs "
        f"({(100 * covered // len(rows)) if rows else 0}% covered).",
        "",
        "| Code | Module | Walkthrough |",
        "|---|---|---|",
    ]
    for r in rows:
        wt = r["walkthrough_title"] or "— **gap**"
        lines.append(f"| `{r['code']}` | {r['module']} | {wt} |")
    return "\n".join(lines) + "\n"
